/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 modern.gltf 
Author: zigurat architecture studio (https://sketchfab.com/ziguratarchitecturestudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-tower-office-apartment-house-home-a057bf3379b24c23a18a82ec884e4f04
Title: modern tower office apartment house home
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/modern.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Box025_Ceramic_0.geometry} material={materials.Ceramic} position={[591.564, 2070.715, -1283.512]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes['Box026_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[-562.884, 0, -939.697]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Box028_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[333.441, 2070.715, -921.102]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes['Box033_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[-50.097, 582.054, -104.859]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes['Line001_06_-_Default_0'].geometry} material={materials['06_-_Default']} position={[92.937, 1625.998, 145.973]} />
        <mesh geometry={nodes['Line005_05_-_Default_0'].geometry} material={materials['05_-_Default']} position={[67.57, 1137.466, 145.923]} />
        <mesh geometry={nodes['Line006_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[-135.9, 544.265, -668.354]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Line015_21_-_Default_0'].geometry} material={materials['21_-_Default']} position={[-259.783, 720.862, 418.803]} />
        <mesh geometry={nodes['Box058_16_-_Matte_Plastic_0'].geometry} material={materials['16_-_Matte_Plastic']} position={[280.28, 209.933, -57.761]} />
        <mesh geometry={nodes['Box062_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[432.418, 301.029, 53.715]} />
        <mesh geometry={nodes['Box068_15_-_Glossy_Plastic_0'].geometry} material={materials['15_-_Glossy_Plastic']} position={[101.189, 375.567, -2030.128]} />
        <mesh geometry={nodes['Line016_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[455.14, 193.598, -155.515]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes['Shape025_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[432.418, 301.029, 13.402]} />
        <mesh geometry={nodes['Box070_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-2523.268, -170.027, -858.2]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Box071_Metal_0.geometry} material={materials.Metal} position={[-2523.268, -154.644, -858.2]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box072_17_-_Old_Copper_#1_0'].geometry} material={materials['17_-_Old_Copper_1']} position={[-2523.268, -158.413, -858.2]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/modern.gltf')
