/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 a.gltf 
Author: Nicolai Kilstrup (https://sketchfab.com/nkilstrup)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/building-brutalist-tricorner-a0923ae832474539bc856a8c6d3acc00
Title: Building Brutalist TriCorner
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/a.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.M_Aircon} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.M_Aircon} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.M_Aircon} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.M_Concrete_02} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.M_Tiles_01} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_13.geometry} material={materials.M_FlakingPaint} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.M_Steel_Shiny} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.M_Cable} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_17.geometry} material={materials.M_Decal_PlasterHoles} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.M_Decal_WallStains} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.M_Stains_02} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.M_Stains_01} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_26.geometry} material={materials.M_Pipes_RustyMetal_01} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.M_Pipes_RustyMetal_01} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.M_Pipes_RustyMetal_01} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_30.geometry} material={materials.M_Concrete_02} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.M_Pipes_RustyMetal_01} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.M_Concrete_01} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_36.geometry} material={materials.M_Stains_01} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.M_Pipes_RustyMetal_01} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.M_Window_01_Frame} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.M_Window_01_Frame} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.M_Window_01_Glass} />
      </group>
      <mesh geometry={nodes.Object_11.geometry} material={materials.M_ClothingLines_01} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.M_Steel_Duct} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.M_Cable} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.M_Roofing_Plastic_01} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/a.gltf')
